---
title: "Timescale-specfic variance ratio (tsvr) package vignette"
author: "Lei Zhao, Shaopeng Wang, Daniel Reuman"
date: ""
geometry: "left=1cm,right=1cm,top=2.5cm,bottom=2.8cm"

output: 
  pdf_document:
    number_sections: yes
    keep_tex: yes
    fig_caption: yes
link-citations: True
urlcolor: blue

bibliography: tsvrvignette_refs.bib 

vignette: >
  %\VignetteIndexEntry{"tsvr vignette"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
This package provides a timescale-specific extension and generalization of the variance ratio
of [@Peterson_75]. The variance ratio is used commonly in community ecology. The extension
implemented here was described by [@Zhao_inprep]. This package supports that paper and provides
the tools developed there for anyone to use. Mathematical formulas for the variance ratio and the 
extensions implemented in this package will not be provided in this vignette - 
see [@Peterson_75; @Hallett_14; @Zhao_inprep] for the mathematics. Instead this vignette
indicates how to use the codes in the package to compute the formulas on data.

# Preparing data for application of the tools 
\noindent A typical dataset for analysis using `tsvr` is an $N \times T$ matrix 
of nonnegative numeric 
values where rows correspond to species in a community (so the number of species is $N$)
and columns correspond to evenly spaced times during which sampling was conducted (so the
number of times sampling was conducted is $T$). Matrix entries may be densities, or percent
cover values, or other measures of abundance of species in an ecological community. For instance:

```{r JRG_data, echo=TRUE}
library(tsvr)
class(JRGdat)
names(JRGdat)
d<-t(as.matrix(JRGdat[,2:dim(JRGdat)[2]]))
dim(d)
```

Here `d` is a $26 \times 28$ matrix containing percent cover measurements for each year from
$1983$ to $2010$ for 26 species which occurred in a 1 m$^2$ plot in Jasper Ridge Biological 
Preserve serpentine grassland site. Species names are in the row names. This data set is
`JRGdat` in the `tsvr` package. Documentation can be viewed via `?JRGdat`. See [@Hallett_14]
for details of the system and of these and other related data.

Standard implementations of Fourier trasforms require time series consisting
of measurements taken at evenly spaced times, with no missing data. The core functions provided
in `tsvr` make these same assumptions and throw an error if data are missing.
The user is left to decide on and implement a reasonable way of filling missing
data, if data are missing and there is a reasonable filling method. We have previously 
used the simple approach of
replacing missing values in a time series by the median of the non-missing values in the
time series [@Sheppard_16]. This approach, and other related simple 
procedures [@Sheppard_16], seem
unlikely to artefactually produce significant synchrony, or 
coherence relationships with other
variables, but rely on the percentage of missing data being fairly low and may obscure 
detection of synchrony or significant coherence relationships if too many data are 
missing. For applications which differ meaningfully from the prior work for which
the tools of this package were developed [@Zhao_inprep],
different ways of dealing with missing data may be more appropriate.

The timescale-specific variance ratio techniques which are the focus of this package
use Fourier methods to decompose by timescale the classic 
variance ratio and related quantities. Detrending and
variance standardization across time series, techniques which are often
applied before doing Fourier analysis, may not be approriate unless it makes sense 
to calculate the classic variance ratio and related quantities after performing those
techniques. And usually it does not.

# The classic variance ratio and related quantities
\noindent The elements of the equation $\text{CV}_{\text{com}}^2 = \varphi \text{CV}_{\text{comip}}^2$
are computed and stored using the 

# The Loreau-de Mazancourt variance ratio and related quantities
\noindent add text

# The timescale-specific classic variance ratio and related quntities
\noindent add text

# The lack of a timescale-specific Loreau-de Mazancourt variance ratio
\noindent add text

# Aggregating timescale-specific variance ratio and related quantities to timescale bands
\noindent add text

# Example using real data
\noindent This could be an analysis of one plot from one site from the grassland data

# Acknowlegements
\noindent This material is based upon work supported by the National Science Foundation 
under grant numbers 17114195 and 1442595, and by the James S McDonnell Foundation. 
Any opinions, findings, and conclusions 
or recommendations expressed in this material are those of the authors and do 
not necessarily reflect the views of the National Science Foundation or the McDonnell Foundation. 
We thank all 
users of the package who have reported or will later report ways in 
which the package could be improved.

# References